#!/bin/bash
rm	silk/decoder
rm	silk/libSKP_SILK_SDK.a
rm	silk/src/SKP_Silk_A2NLSF.o
rm	silk/src/SKP_Silk_CNG.o
rm	silk/src/SKP_Silk_HP_variable_cutoff_FIX.o
rm	silk/src/SKP_Silk_LBRR_reset.o
rm	silk/src/SKP_Silk_LPC_inv_pred_gain.o
rm	silk/src/SKP_Silk_LPC_synthesis_filter.o
rm	silk/src/SKP_Silk_LPC_synthesis_order16.o
rm	silk/src/SKP_Silk_LP_variable_cutoff.o
rm	silk/src/SKP_Silk_LSF_cos_table.o
rm	silk/src/SKP_Silk_LTP_analysis_filter_FIX.o
rm	silk/src/SKP_Silk_LTP_scale_ctrl_FIX.o
rm	silk/src/SKP_Silk_MA.o
rm	silk/src/SKP_Silk_NLSF2A.o
rm	silk/src/SKP_Silk_NLSF2A_stable.o
rm	silk/src/SKP_Silk_NLSF_MSVQ_decode.o
rm	silk/src/SKP_Silk_NLSF_MSVQ_encode_FIX.o
rm	silk/src/SKP_Silk_NLSF_VQ_rate_distortion_FIX.o
rm	silk/src/SKP_Silk_NLSF_VQ_sum_error_FIX.o
rm	silk/src/SKP_Silk_NLSF_VQ_weights_laroia.o
rm	silk/src/SKP_Silk_NLSF_stabilize.o
rm	silk/src/SKP_Silk_NSQ.o
rm	silk/src/SKP_Silk_NSQ_del_dec.o
rm	silk/src/SKP_Silk_PLC.o
rm	silk/src/SKP_Silk_VAD.o
rm	silk/src/SKP_Silk_VQ_nearest_neighbor_FIX.o
rm	silk/src/SKP_Silk_ana_filt_bank_1.o
rm	silk/src/SKP_Silk_apply_sine_window.o
rm	silk/src/SKP_Silk_array_maxabs.o
rm	silk/src/SKP_Silk_autocorr.o
rm	silk/src/SKP_Silk_biquad.o
rm	silk/src/SKP_Silk_biquad_alt.o
rm	silk/src/SKP_Silk_burg_modified.o
rm	silk/src/SKP_Silk_bwexpander.o
rm	silk/src/SKP_Silk_bwexpander_32.o
rm	silk/src/SKP_Silk_code_signs.o
rm	silk/src/SKP_Silk_control_audio_bandwidth.o
rm	silk/src/SKP_Silk_control_codec_FIX.o
rm	silk/src/SKP_Silk_corrMatrix_FIX.o
rm	silk/src/SKP_Silk_create_init_destroy.o
rm	silk/src/SKP_Silk_dec_API.o
rm	silk/src/SKP_Silk_decode_core.o
rm	silk/src/SKP_Silk_decode_frame.o
rm	silk/src/SKP_Silk_decode_parameters.o
rm	silk/src/SKP_Silk_decode_pitch.o
rm	silk/src/SKP_Silk_decode_pulses.o
rm	silk/src/SKP_Silk_decoder_set_fs.o
rm	silk/src/SKP_Silk_detect_SWB_input.o
rm	silk/src/SKP_Silk_div_oabi.o
rm	silk/src/SKP_Silk_enc_API.o
rm	silk/src/SKP_Silk_encode_frame_FIX.o
rm	silk/src/SKP_Silk_encode_parameters.o
rm	silk/src/SKP_Silk_encode_pulses.o
rm	silk/src/SKP_Silk_find_LPC_FIX.o
rm	silk/src/SKP_Silk_find_LTP_FIX.o
rm	silk/src/SKP_Silk_find_pitch_lags_FIX.o
rm	silk/src/SKP_Silk_find_pred_coefs_FIX.o
rm	silk/src/SKP_Silk_gain_quant.o
rm	silk/src/SKP_Silk_init_encoder_FIX.o
rm	silk/src/SKP_Silk_inner_prod_aligned.o
rm	silk/src/SKP_Silk_interpolate.o
rm	silk/src/SKP_Silk_k2a.o
rm	silk/src/SKP_Silk_k2a_Q16.o
rm	silk/src/SKP_Silk_lin2log.o
rm	silk/src/SKP_Silk_log2lin.o
rm	silk/src/SKP_Silk_noise_shape_analysis_FIX.o
rm	silk/src/SKP_Silk_pitch_analysis_core.o
rm	silk/src/SKP_Silk_pitch_est_tables.o
rm	silk/src/SKP_Silk_prefilter_FIX.o
rm	silk/src/SKP_Silk_process_NLSFs_FIX.o
rm	silk/src/SKP_Silk_process_gains_FIX.o
rm	silk/src/SKP_Silk_quant_LTP_gains_FIX.o
rm	silk/src/SKP_Silk_range_coder.o
rm	silk/src/SKP_Silk_regularize_correlations_FIX.o
rm	silk/src/SKP_Silk_resampler.o
rm	silk/src/SKP_Silk_resampler_down2.o
rm	silk/src/SKP_Silk_resampler_down2_3.o
rm	silk/src/SKP_Silk_resampler_down3.o
rm	silk/src/SKP_Silk_resampler_private_AR2.o
rm	silk/src/SKP_Silk_resampler_private_ARMA4.o
rm	silk/src/SKP_Silk_resampler_private_IIR_FIR.o
rm	silk/src/SKP_Silk_resampler_private_copy.o
rm	silk/src/SKP_Silk_resampler_private_down4.o
rm	silk/src/SKP_Silk_resampler_private_down_FIR.o
rm	silk/src/SKP_Silk_resampler_private_up2_HQ.o
rm	silk/src/SKP_Silk_resampler_private_up4.o
rm	silk/src/SKP_Silk_resampler_rom.o
rm	silk/src/SKP_Silk_resampler_up2.o
rm	silk/src/SKP_Silk_residual_energy16_FIX.o
rm	silk/src/SKP_Silk_residual_energy_FIX.o
rm	silk/src/SKP_Silk_scale_copy_vector16.o
rm	silk/src/SKP_Silk_scale_vector.o
rm	silk/src/SKP_Silk_schur.o
rm	silk/src/SKP_Silk_schur64.o
rm	silk/src/SKP_Silk_shell_coder.o
rm	silk/src/SKP_Silk_sigm_Q15.o
rm	silk/src/SKP_Silk_solve_LS_FIX.o
rm	silk/src/SKP_Silk_sort.o
rm	silk/src/SKP_Silk_sum_sqr_shift.o
rm	silk/src/SKP_Silk_tables_LTP.o
rm	silk/src/SKP_Silk_tables_NLSF_CB0_10.o
rm	silk/src/SKP_Silk_tables_NLSF_CB0_16.o
rm	silk/src/SKP_Silk_tables_NLSF_CB1_10.o
rm	silk/src/SKP_Silk_tables_NLSF_CB1_16.o
rm	silk/src/SKP_Silk_tables_gain.o
rm	silk/src/SKP_Silk_tables_other.o
rm	silk/src/SKP_Silk_tables_pitch_lag.o
rm	silk/src/SKP_Silk_tables_pulses_per_block.o
rm	silk/src/SKP_Silk_tables_sign.o
rm	silk/src/SKP_Silk_tables_type_offset.o
rm	silk/src/SKP_Silk_warped_autocorrelation_FIX.o
rm	silk/test/Decoder.o
